In [2]:
import torch

In [6]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [7]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [8]:
print(y.grad_fn)

In [9]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [10]:
a = torch.randn(2, 2)
print(a)
a = ((a * 3) / (a - 1))
print(a)
print(a.requires_grad)
print(a.requires_grad)
b = (a * a).sum()
print(b)
print(b.grad_fn)

tensor([[ 0.8704, -0.3499],
        [ 0.2924, -0.2218]])
tensor([[-20.1428,   0.7776],
        [ -1.2397,   0.5445]])
False
True
tensor(408.1689, grad_fn=<SumBackward0>)


In [11]:
#Gradient, 역전파
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [34]:
#벡터-야코비안 곱
x = torch.randn(3, requires_grad = True)
print(x)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([-1.4656,  1.9278,  0.4656], requires_grad=True)
tensor([-750.3679,  987.0461,  238.3963], grad_fn=<MulBackward0>)


In [35]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [37]:
#연산 추적 피하기
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [41]:
#내용물은 같지만 required_grad가 다른 새로운 Tensor
print(x.requires_grad)
y = x.detach() 
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
