In [8]:
from __future__ import print_function
import torch as tc

In [11]:
x = tc.empty(5, 3)
print(x)

tensor([[8.4490e-39, 9.6428e-39, 1.1112e-38],
        [9.5511e-39, 1.0102e-38, 1.0286e-38],
        [1.0194e-38, 9.6429e-39, 9.2755e-39],
        [9.1837e-39, 9.3674e-39, 1.0745e-38],
        [1.0653e-38, 9.5510e-39, 1.0561e-38]])


In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1804, 0.2884, 0.7018],
        [0.5745, 0.0959, 0.0999],
        [0.3899, 0.5957, 0.8071],
        [0.0548, 0.0704, 0.7168],
        [0.9375, 0.0607, 0.1395]])


In [4]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [11]:
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[ 0.4257,  1.4763,  0.5021],
        [-0.5061, -0.7674, -0.0124],
        [ 0.5170, -0.0550,  0.2482],
        [ 0.5568, -1.5337, -1.1606],
        [ 0.7816, -1.9020,  0.2865]])


In [12]:
print(x.size())

torch.Size([5, 3])


In [13]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.3598,  1.6809,  0.5784],
        [ 0.1630, -0.6378,  0.7402],
        [ 0.8403,  0.6544,  0.6530],
        [ 0.7157, -0.9747, -0.4079],
        [ 1.6738, -1.5333,  0.9330]])


In [14]:
print(torch.add(x, y))

tensor([[ 1.3598,  1.6809,  0.5784],
        [ 0.1630, -0.6378,  0.7402],
        [ 0.8403,  0.6544,  0.6530],
        [ 0.7157, -0.9747, -0.4079],
        [ 1.6738, -1.5333,  0.9330]])


In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[ 1.3598,  1.6809,  0.5784],
        [ 0.1630, -0.6378,  0.7402],
        [ 0.8403,  0.6544,  0.6530],
        [ 0.7157, -0.9747, -0.4079],
        [ 1.6738, -1.5333,  0.9330]])


In [21]:
y.add_(x)
print(y)

tensor([-0.3734, -0.5677, -1.3822, -1.0578,  0.6709,  1.7523,  0.4721, -0.8921,
        -1.3899, -0.2483,  0.5848, -2.6316, -0.6795,  1.0196, -1.7406, -3.9586])


In [17]:
print(x[:, 1])

tensor([ 1.4763, -0.7674, -0.0550, -1.5337, -1.9020])


In [18]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 4)

print(x)
print(y)
print(z)

print(x.size(), y.size(), z.size())

tensor([[-0.0499, -0.2441, -1.0587, -0.7342],
        [ 0.9945,  2.0758,  0.7956, -0.5686],
        [-1.0663,  0.0752,  0.9084, -2.3080],
        [-0.3560,  1.3432, -1.4170, -3.6350]])
tensor([-0.0499, -0.2441, -1.0587, -0.7342,  0.9945,  2.0758,  0.7956, -0.5686,
        -1.0663,  0.0752,  0.9084, -2.3080, -0.3560,  1.3432, -1.4170, -3.6350])
tensor([[-0.0499, -0.2441, -1.0587, -0.7342],
        [ 0.9945,  2.0758,  0.7956, -0.5686],
        [-1.0663,  0.0752,  0.9084, -2.3080],
        [-0.3560,  1.3432, -1.4170, -3.6350]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([4, 4])


In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3235])
-0.32354116439819336


In [23]:
#Torch Tensor를 NumPy 배열로 변환하기
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [24]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [25]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
#NumPy 배열을 Torch Tensor로 변환하기
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
